[package]
name = "component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.windows]
version = "0.43"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_System_WinRT",
]

[build-dependencies]
windows-bindgen = "0.43"
windows-metadata = "0.43"
