[package]
name = "component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.windows]
version = "0.34"
features = [
    "implement",
    "Win32_Foundation",
]

[build-dependencies.windows-bindgen]
version = "0.34"
